dist: app
language: node_js
node_js:
  - "10"
before_script:
  - chmod +x app
  - cd app
  - npm install -g hexo-cli
  - npm install hexo
  - chmod +x hexo generate
  - chmod +x hexo clean
  - chmod +x hexo deploy
  - npm install hexo-deployer-git --save
script: npm test